spring.application.name=task_planner
application.environment=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/task_planner
spring.datasource.username=task_planner
spring.datasource.password=task_planner
jwt.secret=Yq56itqt4Y5oiL6TTI1sbdASrVzEQyH2tPLoj2SuxP0=
jwt.expiration-ms=600000
#spring.jpa.show-sql=true
#logging.level.org.hibernate.orm.jdbc.bind=TRACE